-- Attempt1
-- SELECT Orders.ORDERID, MAX(
--     SELECT SUM(ORDERSDISHES.ORDERSDISHESID) AS ORDER_SUM
--     FROM ORDERSDISHES
--     JOIN ORDERS
--     ON ORDERSDISHES.ORDERID = ORDERS.ORDERID
--     GROUP BY ORDERS.ORDERID
-- ) as ORDERTOTAL
-- FROM Orders
-- INNER JOIN OrdersDishes
-- ON Orders.ORDERID = OrdersDishes.ORDERID
-- GROUP BY Orders.ORDERID;

--Attempt2

SELECT TOP 1 O.OrderID, Sum(d.price) as OrderTotal
FROM ORDERS as O
INNER JOIN ORDERSDISHES AS od on O.ORDERID = od.ORDERID
INNER JOIN DISHES AS d on od.DISHID = d.DISHID
GROUP BY od.ORDERID
ORDER BY OrderTotal DESC;
