

SELECT TOP 1 O.OrderID, Sum(d.price) as OrderTotal
FROM ORDERS as O
INNER JOIN ORDERSDISHES AS od on O.ORDERID = od.ORDERID
INNER JOIN DISHES AS d on od.DISHID = d.DISHID
GROUP BY od.ORDERID
ORDER BY OrderTotal DESC;
