-- SQL request(s)​​​​​​‌​‌​​‌​​‌​​​​‌‌​​‌‌‌​​​‌‌ below
SELECT AVG(ORDERAVERAGE)
FROM (
    SELECT SUM(DISHES.Price) AS ORDERAVERAGE
    FROM ORDERS
    INNER JOIN ORDERSDISHES
    ON ORDERS.ORDERID = ORDERSDISHES.ORDERID
    INNER JOIN DISHES
    ON DISHES.DISHID = OrdersDishes.DISHID
    GROUP BY ORDERS.ORDERID
);